[[entry]]
played_at = "2026-07-18T16:05:33Z"
path = "VCE_Audio/32 - Metallica - Enter Sandman.mp3"
title = "Enter Sandman"
artist = "Metallica"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 32

[[entry]]
played_at = "2026-07-14T19:54:51Z"
path = "VCE_Audio/17 - Flume - Never Be Like You.mp3"
title = "Never Be Like You"
artist = "Flume"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 17

[[entry]]
played_at = "2026-07-12T17:30:52Z"
path = "VCE_Audio/28 - Kendrick Lamar - Alright.mp3"
title = "Alright"
artist = "Kendrick Lamar"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 28

[[entry]]
played_at = "2026-07-12T17:28:49Z"
path = "VCE_Audio/26 - Johnny Cash - Hurt.mp3"
title = "Hurt"
artist = "Johnny Cash"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 26

[[entry]]
played_at = "2026-07-12T17:21:49Z"
path = "VCE_Audio/26 - Johnny Cash - Hurt.mp3"
title = "Hurt"
artist = "Johnny Cash"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 26

[[entry]]
played_at = "2026-07-12T17:12:49Z"
path = "VCE_Audio/25 - John Williams - The Imperial March.mp3"
title = "The Imperial March"
artist = "John Williams"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 25

[[entry]]
played_at = "2026-07-12T17:02:28Z"
path = "VCE_Audio/25 - John Williams - The Imperial March.mp3"
title = "The Imperial March"
artist = "John Williams"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 25

[[entry]]
played_at = "2026-07-09T19:25:34Z"
path = "VCE_Audio/24 - John Cage - Sonata V.mp3"
title = "Sonata V"
artist = "John Cage"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 24

[[entry]]
played_at = "2026-07-09T19:20:32Z"
path = "VCE_Audio/24 - John Cage - Sonata V.mp3"
title = "Sonata V"
artist = "John Cage"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 24

[[entry]]
played_at = "2026-07-09T19:07:59Z"
path = "VCE_Audio/24 - John Cage - Sonata V.mp3"
title = "Sonata V"
artist = "John Cage"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 24

[[entry]]
played_at = "2026-07-09T18:57:37Z"
path = "VCE_Audio/23 - James Brown - I Got You (I Feel Good).mp3"
title = "I Got You (I Feel Good)"
artist = "James Brown"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 23

[[entry]]
played_at = "2026-07-08T15:18:17Z"
path = "VCE_Audio/23 - James Brown - I Got You (I Feel Good).mp3"
title = "I Got You (I Feel Good)"
artist = "James Brown"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 23

[[entry]]
played_at = "2026-07-05T15:17:55Z"
path = "VCE_Audio/22 - J.S. Bach - Fugue in G minor, BWV 578 (Little Fugue).mp3"
title = "Fugue in G minor, BWV 578 (Little Fugue)"
artist = "J.S. Bach"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 22

[[entry]]
played_at = "2026-07-04T19:43:51Z"
path = "Leisure/Ampyx - Sunset Surf.mp3"
title = "Ampyx - Sunset Surf"
artist = "Ampyx"
album = "Ampyx - Sunset Surf"
genre = "Music"
year = 2026

[[entry]]
played_at = "2026-07-04T19:01:19Z"
path = "VCE_Audio/20 - Hans Zimmer - Time.mp3"
title = "Time"
artist = "Hans Zimmer"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 20

[[entry]]
played_at = "2026-07-04T18:46:49Z"
path = "VCE_Audio/20 - Hans Zimmer - Time.mp3"
title = "Time"
artist = "Hans Zimmer"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 20

[[entry]]
played_at = "2026-07-03T19:40:39Z"
path = "VCE_Audio/16 - Ennio Morricone - The Ecstasy of Gold.mp3"
title = "The Ecstasy of Gold"
artist = "Ennio Morricone"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 16

[[entry]]
played_at = "2026-07-03T17:44:28Z"
path = "VCE_Audio/16 - Ennio Morricone - The Ecstasy of Gold.mp3"
title = "The Ecstasy of Gold"
artist = "Ennio Morricone"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 16

[[entry]]
played_at = "2026-07-03T17:37:00Z"
path = "VCE_Audio/16 - Ennio Morricone - The Ecstasy of Gold.mp3"
title = "The Ecstasy of Gold"
artist = "Ennio Morricone"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 16

[[entry]]
played_at = "2026-07-03T16:38:09Z"
path = "VCE_Audio/16 - Ennio Morricone - The Ecstasy of Gold.mp3"
title = "The Ecstasy of Gold"
artist = "Ennio Morricone"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 16

[[entry]]
played_at = "2026-07-02T21:20:25Z"
path = "VCE_Audio/14 - Deadmau5 - Strobe.mp3"
title = "Strobe"
artist = "Deadmau5"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 14

[[entry]]
played_at = "2026-07-02T07:37:42Z"
path = "VCE_Audio/14 - Deadmau5 - Strobe.mp3"
title = "Strobe"
artist = "Deadmau5"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 14

[[entry]]
played_at = "2026-07-01T17:54:38Z"
path = "VCE_Audio/15 - Claude Debussy - Clair de Lune.mp3"
title = "Clair de Lune"
artist = "Claude Debussy"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 15

[[entry]]
played_at = "2026-07-01T16:14:14Z"
path = "VCE_Audio/15 - Claude Debussy - Clair de Lune.mp3"
title = "Clair de Lune"
artist = "Claude Debussy"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 15

[[entry]]
played_at = "2026-07-01T16:06:29Z"
path = "VCE_Audio/15 - Claude Debussy - Clair de Lune.mp3"
title = "Clair de Lune"
artist = "Claude Debussy"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 15

[[entry]]
played_at = "2026-07-01T16:00:04Z"
path = "VCE_Audio/09 - Björk - Hyperballad.mp3"
title = "Hyperballad"
artist = "Björk"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 9

[[entry]]
played_at = "2026-06-30T18:13:49Z"
path = "VCE_Audio/09 - Björk - Hyperballad.mp3"
title = "Hyperballad"
artist = "Björk"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 9

[[entry]]
played_at = "2026-06-30T17:58:02Z"
path = "VCE_Audio/09 - Björk - Hyperballad.mp3"
title = "Hyperballad"
artist = "Björk"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 9

[[entry]]
played_at = "2026-06-28T05:16:51Z"
path = "VCE_Audio/07 - Avicii - Levels.mp3"
title = "Levels"
artist = "Avicii"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 7

[[entry]]
played_at = "2026-06-27T15:13:39Z"
path = "VCE_Audio/04 - Arnold Schoenberg - Nacht (No. 8) from Pierrot Lunaire.mp3"
title = "Nacht (No. 8) from Pierrot Lunaire"
artist = "Arnold Schoenberg"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 4

[[entry]]
played_at = "2026-06-27T02:46:54Z"
path = "VCE_Audio/03 - Aretha Franklin - Respect.mp3"
title = "Respect"
artist = "Aretha Franklin"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 3

[[entry]]
played_at = "2026-06-27T02:05:02Z"
path = "VCE_Audio/01 - Antonio Vivaldi - Winter (1st movement: Allegro non molto).mp3"
title = "Winter (1st movement: Allegro non molto)"
artist = "Antonio Vivaldi"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 1

[[entry]]
played_at = "2026-06-26T06:39:01Z"
path = "VCE_Audio/02 - Aphex Twin - Avril 14th.mp3"
title = "Avril 14th"
artist = "Aphex Twin"
album = "VCE Music SAC Revision"
genre = "Classical/Various"
year = 2026
track_number = 2

[[entry]]
played_at = "2026-05-24T05:47:38Z"
path = "Piano/Kinderszenen, Op. 15: VII. Träumerei - Live.mp3"
title = "Kinderszenen, Op. 15: VII. Träumerei - Live"
artist = "Robert Schumann/Vladimir Horowitz"
album = "Vladimir Horowitz - Horowitz in Moscow"
year = 1986

[[entry]]
played_at = "2026-05-24T05:30:45Z"
path = "Leisure/Ray Tracer.mp3"
title = "Ray Tracer"
artist = "TheFatRat/Sprites"
album = "Unity - 10th Anniversary Compilation"
year = 2024

[[entry]]
played_at = "2026-05-20T09:28:41Z"
path = "Leisure/Close To The Sun.mp3"
title = "Close To The Sun"
artist = "TheFatRat/Anjulie"
album = "Unity - 10th Anniversary Compilation"
year = 2024

[[entry]]
played_at = "2026-05-20T09:21:27Z"
path = "Leisure/Mirage - for Assassin's Creed Mirage.mp3"
title = "Mirage - for Assassin's Creed Mirage"
artist = "OneRepublic/Assassin's Creed/Mishaal Tamer"
album = "Mirage (for Assassin's Creed Mirage)"
year = 2023

[[entry]]
played_at = "2026-05-08T10:23:05Z"
path = "Partita - Argerich.flac"
title = "Bach: Partita for keyboard No. 2 | Martha Argerich, piano"
artist = "DW Classical Music"
genre = "Music"
year = 1
